name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  docker:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make informations
        id: docker_info
        run: |
          echo ::set-output name=OWNER::`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          echo ::set-output name=YMD_TAG::`date +"%Y.%m.%d-\`git rev-parse --short ${{ github.sha }}\`"`
      - name: Build (and optionally push) the Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ !github.event.pull_request.head.repo.fork }}
          tags: ghcr.io/${{ steps.docker_info.outputs.OWNER }}/ranol-bot:latest,ghcr.io/${{ steps.docker_info.outputs.OWNER }}/ranol-bot:${{ steps.docker_info.outputs.YMD_TAG }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
