name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  docker:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make yyyy.mm.dd-sha tag
        id: make_yyyy_mm_dd_sha_tag
        run: |
          echo ::set-output tag=`date +"%Y.%m.%d-${{ github.sha }}"`
      - name: Build (and optionally push) the Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ !github.event.pull_request.head.repo.fork }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ranol-bot:latest
            ghcr.io/${{ github.repository_owner }}/ranol-bot:${{ steps.make_yyyy_mm_dd_sha_tag.outputs.tag }}
